name: Say Hello

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        uses: cycdpoCodeLab/hello-world-docker-action@main
        with:
          who-to-greet: 'Mona the Octocat'
